version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # On installe au root (monorepo), puis on lance le dev de web
    working_dir: /app
    ports:
      - "0.0.0.0:5173:5173"
    volumes:
      - .:/app
      # isole tous les node_modules dans des volumes nommés (pas sur l’hôte)
      - root_node_modules:/app/node_modules
      - web_node_modules:/app/apps/web/node_modules
      - ui_node_modules:/app/packages/ui/node_modules
      # cache pnpm (rapide)
      - pnpm_store:/root/.local/share/pnpm/store/v3
    environment:
      NODE_ENV: development
    command: >
      sh -c "
      pnpm install --frozen-lockfile &&
      pnpm --filter web dev --host 0.0.0.0 --port 5173 --strictPort
      "

volumes:
  root_node_modules:
  web_node_modules:
  ui_node_modules:
  pnpm_store:
