version: "3.9"

services:
  dev-builder:
    image: node:20-alpine
    working_dir: /repo
    volumes:
      - ../..:/repo
      - pnpm_store:/root/.local/share/pnpm/store/v3
    environment:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      NODE_ENV: development
    command: >
      sh -lc "
      corepack enable &&
      pnpm -w install &&
      pnpm --filter @repo/types build:watch
      "
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api:
    image: node:20-alpine
    depends_on:
      - postgres
      - dev-builder
    working_dir: /repo/apps/api
    ports:
      - "3333:3333"
      - "9229:9229"
    env_file:
      - ../../.env
    environment:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      PG_HOST: postgres
      NODE_ENV: development
    volumes:
      - ../..:/repo
      - pnpm_store:/root/.local/share/pnpm/store/v3
    command: >
      sh -lc "
      corepack enable &&
      pnpm -w install &&
      node ../..//apps/api/ace migration:run --force &&
      node ../..//apps/api/ace db:seed &&
      pnpm dev
      "

  web:
    image: node:20-alpine
    depends_on:
      - api
      - dev-builder
    working_dir: /repo/apps/web
    ports:
      - "5173:5173"
    environment:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      NODE_ENV: development
    volumes:
      - ../..:/repo
      - pnpm_store:/root/.local/share/pnpm/store/v3
    command: >
      sh -lc "
      corepack enable &&
      pnpm -w install &&
      pnpm --filter web dev --host 0.0.0.0 --port 5173 --strictPort
      "
volumes:
  pnpm_store:
  postgres_volume:
