services:
  web:
    build:
      context: ../../apps/web
      dockerfile: dockerfile
    working_dir: /app
    ports:
      - "0.0.0.0:5173:5173"
    volumes:
      - ../../:/app
      - root_node_modules:/app/node_modules
      - web_node_modules:/app/apps/web/node_modules
      - ui_node_modules:/app/packages/ui/node_modules
      - pnpm_store:/root/.local/share/pnpm/store/v3
    environment:
      NODE_ENV: development
    command: >
      sh -c "
      pnpm install --frozen-lockfile &&
      pnpm --filter web dev --host 0.0.0.0 --port 5173 --strictPort
      "

  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
    build:
      context: ../../apps/api
      dockerfile: dockerfile
    working_dir: /home/node/app
    ports:
      - "3333:3333"
      - "9229:9229"
    env_file:
      - ../../.env
    environment:
      - PG_HOST=postgres
    volumes:
      - ../../apps/api:/home/node/app
      - api_node_modules:/home/node/app/node_modules
      - api_pnpm_store:/root/.local/share/pnpm/store/v3
    command: >
      sh -c "pnpm install && pnpm dev"

volumes:
  root_node_modules:
  api_node_modules:
  api_pnpm_store:
  web_node_modules:
  ui_node_modules:
  pnpm_store:
  postgres_volume:
