services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mindlapse_db
    ports: ["5432:5432"]
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  adonis_app:
    container_name: adonis_app
    depends_on:
      - postgres
    build:
      context: ../../apps/api
      dockerfile: dockerfile
    working_dir: /repo/apps/api
    ports:
      - "3333:3333"
      - "9229:9229"
    env_file:
      - ../../.env
    environment:
      NODE_ENV: development
      PG_HOST: postgres
    volumes:
      - ../..:/repo
      - pnpm_store:/root/.local/share/pnpm/store/v3
      - root_node_modules:/repo/node_modules
      - web_node_modules:/repo/apps/web/node_modules
      - ui_node_modules:/repo/packages/ui/node_modules
    command: >
      sh -lc "
        corepack enable &&
        pnpm -w install --config.package-import-method=copy &&
        pnpm --filter @repo/types run build &&
        pnpm --filter api install --config.package-import-method=copy &&
        pnpm --filter api exec node ace migration:run&&
        pnpm --filter api exec node ace db:seed &&
        pnpm --filter api dev
      "

  web:
    build:
      context: ../../apps/web
    working_dir: /repo/apps/web
    depends_on:
      - adonis_app
    ports:
      - "0.0.0.0:5173:5173"
    environment:
      NODE_ENV: development
    volumes:
      - ../..:/repo
      - pnpm_store:/root/.local/share/pnpm/store/v3
      - api_node_modules:/repo/apps/api/node_modules
      - root_node_modules:/repo/node_modules
      - web_node_modules:/repo/apps/web/node_modules
      - ui_node_modules:/repo/packages/ui/node_modules
    command: >
      sh -lc "
        corepack enable &&
        pnpm config set auto-install-peers true &&
        pnpm -w install --no-frozen-lockfile --config.package-import-method=copy &&
        pnpm --filter @repo/ui install --no-frozen-lockfile --config.package-import-method=copy &&
        pnpm --filter web install --no-frozen-lockfile --config.package-import-method=copy &&
        pnpm --filter @repo/ui run build &&
        pnpm exec vite -- --clearScreen false --host 0.0.0.0 --port 5173 --strictPort
      "

volumes:
  pnpm_store:
  postgres_volume:
  root_node_modules:
  web_node_modules:
  ui_node_modules:
  api_node_modules:
