import { BaseSeeder } from '@adonisjs/lucid/seeders'
import db from '@adonisjs/lucid/services/db'

export default class extends BaseSeeder {
  public static developmentOnly = true

  async run() {
    const now = new Date()
    await db.table('droids').insert([
      {
        name: 'R5-series',
        slug: 'r5-series',
        description:
          'Astromech de soutien pour navigation et diagnostics basiques, robuste et économique.',
        type: 'ASTROMECH',
        maker: 'INDUSTRIAL_AUTOMATON',
        price: 10999.0,
        stock: 7,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'R4-series',
        slug: 'r4-series',
        description: 'Astromech fiable pour chasseurs légers, orienté maintenance sur le terrain.',
        type: 'ASTROMECH',
        maker: 'INDUSTRIAL_AUTOMATON',
        price: 12999.0,
        stock: 0,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'MSE-6 series',
        slug: 'mse-6-series',
        description:
          'Micro-droïde utilitaire (“souris”) pour inspections, messages et petites réparations.',
        type: 'REPAIR',
        maker: 'INDUSTRIAL_AUTOMATON',
        price: 1499.0,
        stock: 12,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'GNK-series',
        slug: 'gnk-series',
        description: 'Unité d’alimentation mobile pour bases avancées et ateliers de fortune.',
        type: 'REPAIR',
        maker: 'INDUSTRIAL_AUTOMATON',
        price: 3999.0,
        stock: 4,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'CZ-series',
        slug: 'cz-series',
        description: 'Droïde de communication et d’inventaire, idéal pour entrepôts et comptoirs.',
        type: 'PROTOCOL',
        maker: 'CYBOT_GALACTIC',
        price: 6999.0,
        stock: 5,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'EV-series',
        slug: 'ev-series',
        description:
          'Superviseur d’atelier/astroport, gestion des tâches et conformité de sécurité.',
        type: 'PROTOCOL',
        maker: 'CYBOT_GALACTIC',
        price: 11999.0,
        stock: 0,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'WA-7',
        slug: 'wa-7',
        description: 'Service et accueil clientèle, protocole basique et logistique légère.',
        type: 'PROTOCOL',
        maker: 'CYBOT_GALACTIC',
        price: 4499.0,
        stock: 9,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'FX-series',
        slug: 'fx-series',
        description: 'Assistant médical polyvalent, triage et soins standard.',
        type: 'MEDICAL',
        maker: 'CYBOT_GALACTIC',
        price: 13999.0,
        stock: 4,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: '2-1B',
        slug: '2-1b',
        description: 'Droïde chirurgien spécialisé, stérilisation et implants bioniques.',
        type: 'MEDICAL',
        maker: 'INDUSTRIAL_AUTOMATON',
        price: 21999.0,
        stock: 2,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'KX-series',
        slug: 'kx-series',
        description: 'Sécurité industrielle et escorte, force dissuasive et analyse des menaces.',
        type: 'COMBAT',
        maker: 'KUAT_SYSTEMS_ENGINEERING',
        price: 18999.0,
        stock: 3,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'KSE-4',
        slug: 'kse-4',
        description: 'Garde statique/portuaire, routines de contrôle d’accès et patrouille.',
        type: 'COMBAT',
        maker: 'KUAT_SYSTEMS_ENGINEERING',
        price: 15999.0,
        stock: 4,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'Kuat flight',
        slug: 'kuat-flight',
        description:
          'Assistance aux hangars et au trafic spatial, coordination décollages/atterrissages.',
        type: 'PILOT',
        maker: 'KUAT_SYSTEMS_ENGINEERING',
        price: 9999.0,
        stock: 5,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'IG-series',
        slug: 'ig-series',
        description: 'Plateforme tactique polyvalente, ciblage haute précision et dissimulation.',
        type: 'COMBAT',
        maker: 'HOLOWAN_ARMAMENT',
        price: 28999.0,
        stock: 2,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
      {
        name: 'Holowan field support',
        slug: 'holowan-field-support',
        description: 'Soutien technique avancé sur théâtre d’opérations : réparation et munitions.',
        type: 'REPAIR',
        maker: 'HOLOWAN_ARMAMENT',
        price: 11999.0,
        stock: 3,
        image_url: null,
        created_at: now,
        updated_at: now,
      },
    ])
  }
}
